# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Build
      run: CC=clang go build -v -o stock-monitor ./main.go

    - name: Generate Tag
      run: echo "release_tag=auto-release-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ env.release_tag }}
        files: stock-monitor

    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
